version: '3'
services: 
  db: 
    image: mysql/mysql-server:5.7
    volumes: 
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    env_file:
      - settings.env
    ports:
      - "3000:3000"
    depends_on:
      - db
